#!/bin/bash

# this is a multi-package directory.  org.cmyers.practice.N and
# org.cmyers.practice.N.release will both have the same prefix and build out of the
# same package directory to avoid littering all over the place in this repo.

if [[ "$PACKAGE_NAME" =~ release$ ]]; then
    # release package
    SRC_PKG=$(echo $PACKAGE_NAME | sed -e 's/\.release$//g')
    echo "SRC PKG: $SRC_PKG"

    $INPUT_ARTIFACTS_DIR/weak/qbt_fringe.wrapper_generator.release/strong/qbt_fringe.wrapper_generator.release/bin/wrapper_generator $INPUT_ARTIFACTS_DIR/weak/$SRC_PKG/strong $OUTPUT_ARTIFACTS_DIR main ${SRC_PKG}.Main
    exit 0;
fi

# normal package
exec $INPUT_ARTIFACTS_DIR/weak/misc1.java_build_process/strong/misc1.java_build_process/bin/java-build-process
